### ISSUE TITLE
Request: Option to automatically "disable inbox replies" for Removal Reasons.

### ISSUE THREAD

**Issue by libbykino** [creesch/reddit-moderator-toolbox#610]
Reddit added the ability to "disable inbox replies" on comments about 8 months ago and it's a great feature that would come in handy when automatically replying to posts/comments via Removal Reasons.  I use the "footer" to direct people to send a modmail message instead of replying, but of course users still reply to the comment anyway.  I can manually go through my replies and hit the "disable inbox replies" button on each of them, but it would be wonderful if Toolbox could do this for me automatically when it comments for me.

Not sure if it's possible, just really hoping that it is.

**Comment by creesch** [comment]
We can implement that and I guess we will. Though to be honest I rather be notified of replies by users personally. 

In /r/history we apply a "locked" flair class and let automod lock the thread after removing something. With a bit of css it works out rather well.

**Comment by libbykino** [comment]
I can definitely understand some people wanting to see the replies, but it would be great to have the option not to.

And I can see locking a thread following a removal being *super* useful.  Though, we don't have "locking" set up in our CSS at /r/gameofthrones yet.  I'll look into it, thanks!

**Comment by creesch** [comment]
This is the css we use in /r/history 

```css
/* Hide reply stuff on locked comments. Also show a message indicacting it has been locked.
---------------------------------*/

.post-linkflair-locked .usertext.cloneable,
.post-linkflair-locked .usertext-edit,
.post-linkflair-locked .reply-button,
.post-linkflair-locked .edit-usertext
 {
    display: none !important;
}

.post-linkflair-locked .commentarea .menuarea:after {
  display: block;
  content:  "This thread is locked. Any new comments will be automatically removed.";
  font-size: 25px;
  margin: 10px 10px 10px 0;
}

```

and this the automod rule 

```yaml
    # Locked threads, simply use the locked threads flair. 
    type: comment
    parent_submission:
        flair_css_class: "locked"
    action: remove
    action_reason: thread is locked
```
