### ISSUE TITLE
Modlog filtering

### ISSUE THREAD

**Issue by amici-ursi** [creesch/reddit-moderator-toolbox#695]
Can we have filtering in the modlog?

Native modlog supports showing _only_ this action, or _only_ this user. However, there is no way to show everything _except_ this action, or _except_ this user.

**Comment by creesch** [comment]
Might be possible, but depending on the filters it might not work that well considering that unless there are some hidden api calls we would need to just filter out on the page. So you might end up with pages of empty stuff before you finally hit something. 

replacing modlog with out api based version is also tricky since the modlog json is missing a lot of information. 


So yeah, I am totally open for the idea but the approach will needs some proper brainstorming.

**Comment by LiterallyWTH** [comment]
Could easily collapse columns and rows.  That way we could generate the parent classes using the same info we use to generate the table, pulling from the existing dropdown.

I just tested it to be sure, it collapses perfectly as if they weren't there.

```css
.hide-creesch .moderator-creesch.mod-row {
    display: none;
}
.hide-approvelink .action-approvelink {
    display: none;
}
```

It doesn't require sending a new request to hide or unhide, and we could hide/show as many as we wish.
